# Generated by Django 2.2.7 on 2020-01-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191220_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='extra_cheese',
            field=models.BooleanField(default=False),
        ),
    ]
