# Generated by Django 2.2.7 on 2020-01-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_item_extra_cheese'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='add_ons',
            field=models.BooleanField(default=False),
        ),
    ]
