# Generated by Django 2.2.7 on 2020-01-03 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_item_add_ons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='topping1',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='topping2',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='topping3',
        ),
        migrations.AddField(
            model_name='purchase',
            name='extra_cheese_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='items', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Item'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1),
        ),
        migrations.CreateModel(
            name='Add_On',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='add_on', to='orders.Topping')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='add_ons',
            field=models.ManyToManyField(blank=True, related_name='items', to='orders.Add_On'),
        ),
    ]
