# Generated by Django 2.2.7 on 2020-01-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200103_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1, null=True),
        ),
    ]
